### ISSUE TITLE
jquery-ui presence breaks intellisense

### ISSUE THREAD

**Issue by natsnudasoft** [natsnudasoft/Tickomon#3]
The presence of `/// <reference path="lib/jquery-ui/jquery-ui.js" />` in [_references.js](https://github.com/natsnudasoft/Tickomon/blob/7dcf668e547d6d85eb51c998ab1d3b22e75551a3/src/Tickomon.Web/wwwroot/_references.js#L6), seems to be breaking javascript intellisense. We have a couple of options here:

1. Remove the jquery-ui reference path and set autosync to false in _references.js, meaning we will have to manually update reference paths whenever we add or remove client-side packages if we want intellisense for them.
2. Downgrading to an earlier version of jquery apparently fixed it for [this](http://stackoverflow.com/a/40412168) person.
3. Add an empty jquery-ui-vsdoc.js file as shown [here](http://stackoverflow.com/a/571834), to the appropriate folder in lib (currently this folder is ignored by git and auto generated by the package manager, but an exception for this single file being added to workaround this issue would be acceptable).

Option 2 is the only one that potentially might keep intellisense for jquery-ui but I am currently leaning towards option 3 so we can keep the most recent version of jquery, and we would still have intellisense for other libraries, just not jquery-ui.

**Comment by deanobob** [comment]
Yeah option 3 makes sense, we can live without intellisense for jquery until they fix VS.

**Comment by natsnudasoft** [comment]
@deanobob Well, it should only disable jquery-ui intellisense which is just a separate library that gives a few ui effects and stuff like dragging and dropping etc. intellisense for the base jquery library should work with any of the proposed options.

**Comment by natsnudasoft** [comment]
Ok, this seems to be causing the jquery-ui library to not be restored by bower now. Will need to investigate other solutions.
